version: "3"

services:
  app:
    container_name: react-app-dev
    build:
      context: .
      target: development
    entrypoint: ./.docker/entrypoints/dev.sh
    volumes:
      - .:/home/app
      - ./node_modules:/home/app/node_modules
    ports:
      - 4000:3000
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
