version: '3'

services:
  app:
    container_name: nestjs-app-production
    image: drack112/teamseas-nestjs
    build:
      context: .
      target: production
    volumes:
      - .:/home/node/app
      - ./node_modules:/home/node/app/node_modules
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - 3000:3000
    env_file:
      - .env
    networks:
      - webnet
    depends_on:
      - db
    extra_hosts:
      - 'host.docker.internal:172.17.0.1'

  db:
    container_name: postgres-database-production
    build: .docker/postgres
    networks:
      - webnet
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - ./.docker/dbdata:/var/lib/postgresql/data
      - ./.docker/postgres:/docker-entrypoint-initdb.d
    env_file:
      - .env

networks:
  webnet:
    driver: bridge
