version: '3'

services:
  app:
    container_name: nestjs-app-contaner
    image: drack112/teamseas-nestjs
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - 3000:3000
    command: 'yarn docker:prod'
    env_file:
      - .env
    networks:
      - webnet
    depends_on:
      - db
    extra_hosts:
      - 'host.docker.internal:172.17.0.1'

  db:
    container_name: postgres-database
    build: ../postgres
    networks:
      - webnet
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - ./../dbdata:/var/lib/postgresql/data
      - ./../postgres:/docker-entrypoint-initdb.d
    env_file:
      - .env

networks:
  webnet:
    driver: bridge
